version: '3'

services:

  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./nginx
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - app

  app:
    container_name: app
    build:
      context: ./node
    tty: true
    volumes:
      - ./node:/usr/src/app
    entrypoint: sh -c "npm install && node index.js"
    networks:
      - node-network
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    restart: always
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    tty: true
    volumes:
      - ./mysql/db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 3

networks:
  node-network:
    driver: bridge